# Generated by Django 4.2.16 on 2024-10-03 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemeTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image_url', models.URLField()),
                ('default_top_text', models.CharField(blank=True, max_length=100)),
                ('default_bottom_text', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
