# Generated by Django 4.2.16 on 2024-10-04 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meme_generator', '0004_alter_rating_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='score',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
    ]
