# Generated by Django 4.2.16 on 2024-10-04 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meme_generator', '0006_alter_memetemplate_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='memetemplate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='templates/'),
        ),
    ]
