# Generated by Django 4.2.16 on 2024-10-05 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meme_generator', '0008_meme_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memetemplate',
            name='image_url',
        ),
    ]
